server:
  port: 7102

spring:
  application:
    name: base-microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lavigne-yang/piclib-config.git
          default-label: main        # 一定要配置，因为github升级后，已经没有 master 分支了， 而config server 默认是 master,  现在已经是 main
    bus: # 开启bus消息总线
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: 47.106.189.240

  security:
    user:
      name: admin
      password: a


eureka:
  client:
    service-url:
      defaultZone: http://admin:a@localhost:1001/eureka
  instance:
    prefer-ip-address: true
    instance-id: microservice-config-02
management:
  endpoints:
    web:
      exposure:
        include: "*"