#server:
#  port: 9101
#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://admin:a@eureka1:1001/eureka
#
#turbine:
#  app-config: MICROSERVICE-PROVIDER,MICROSERVICE-PROVIDER-USER  #需要收集信息的服务名
#  cluster-name-expression: new String("default")
#  combine-host-port: true # 同一主机上的服务通过主机名和端口号的组合来进行区分，默认以host来区分

spring:
  application:
    name: base-microservice-hystrix-turbine
  cloud:
    bus: # 开启bus消息总线
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: 47.106.189.240
